#!/usr/bin/env python
# coding: utf-8
#
import xmlrpclib
import subprocess
import sys
import os

server_host = 'localhost'
program = os.path.basename(sys.argv[0])

if len(sys.argv)-1 <= 1:
    sys.exit('Usage: %s <docker-id> cmd...' % program)

docker_id = sys.argv[1]
args = sys.argv[2:]

try:
    server = subprocess.check_output(['docker', 'port', docker_id, '8000'])
except subprocess.CalledProcessError as e:
    sys.exit(str(e))

try:
    proxy = xmlrpclib.ServerProxy("http://"+server.replace('0.0.0.0', server_host))
    sys.stdout.write(proxy.run(*args))
except xmlrpclib.Fault as e:
    sys.exit(str(e))
